---
- name: Make HomelabOS data directories.
  file:
    path: "/var/homelabos/{{ item }}"
    state: directory
  loop:
    - docker
    - docs
    - docs/docs
    - emby
    - gitea_db
    - grafana
    - homeassistant
    - influxdb
    - nextcloud
    - nextcloud_db
    - pihole
    - pihole/config
    - pihole/dnsmasq.d
    - telegraf
    - traefik

- name: Configure Telegraf.
  template: src=telegraf.conf dest=/var/homelabos/telegraf/telegraf.conf

- name: Configure Traefik.
  template: src=traefik.toml dest=/var/homelabos/traefik/traefik.toml

- name: Configure HomelabOS Documentation
  template: src=mkdocs.yml dest=/var/homelabos/docs/mkdocs.yml

- name: Configure HomelabOS Documentation
  template:
    src: '{{ item.src }}'
    dest: /var/homelabos/docs/docs/{{ item.path }}
    force: yes
  with_filetree: docs/
  when: item.state == 'file'

- name: Configure HomelabOS systemd service.
  template: src=homelabos.service dest=/etc/systemd/system/homelabos.service

- name: Copy HomelabOS docker-compose.yml file into place.
  template:
    src: docker-compose.yml
    dest: /var/homelabos/docker/docker-compose.yml

- name: Pull latest HomelabOS service docker images.
  command: docker-compose -f /var/homelabos/docker/docker-compose.yml pull

- name: Restart HomelabOS service.
  systemd:
    name: homelabos
    enabled: yes
    daemon-reload: yes
    state: restarted

- debug:
    msg: "HomelabOS Installed successfully! Go to http://docs.{{ domain }}/ to get started."