version: '3'
services:
  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - /var/homelabos/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    ports:
      - 8123:8123
      - 1883:1883
      # - 8080:8080
      - 51827:51827
    links:
      - influxdb
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:homeassistant.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=8123"

  emby:
    image: emby/embyserver:latest
    network_mode: host
    restart: always
    volumes:
      - /var/homelabos/emby:/config
    ports:
      - 8096:8096
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:emby.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=8096"

  influxdb:
    image: influxdb
    restart: always
    volumes:
      - /var/homelabos/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  chronograf:
    image: chronograf
    restart: always
    links:
      - influxdb
    ports:
      - 8888:8888
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:chronograf.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=8888"

  grafana:
    image: grafana/grafana
    restart: always
    links:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - /var/homelabos/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,petrslavotinek-carpetplot-panel,vonage-status-panel
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:grafana.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=3000"

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - /var/homelabos/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb

  traefik:
    image: traefik # The official Traefik docker image
    restart: always
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443" # HTTPS
      - "8080:8080" # The Web UI (enabled by --api)
    labels:
      - "traefik.frontend.rule=Host:{{ domain }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/homelabos/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/homelabos/traefik/acme.json:/etc/traefik/acme.json

  whoami:
    image: emilevauge/whoami # A container that exposes an API to show its IP address
    restart: always
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      - "traefik.frontend.rule=PathPrefixStrip:/test"

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - /var/homelabos/docs:/docs
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:docs.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=8000"