version: '3'

services:

  chronograf:
    image: chronograf
    restart: always
    links:
      - influxdb
    ports:
      - 8888:8888
    environment:
      - influxdb-url=http://influxdb:8086
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:chronograf.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=8888"

  darksky-influx:
    image: erwinsteffens/darksky-influxdb:latest
    restart: always
    links:
      - influxdb
    environment:
      - DARKSKY_KEY={{ darksky_key }}
      # This is every 2 minutes. This is about as fast as you can go with the free API keys without running out of queries.
      - CRON=0 */2 * * * *
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_DATABASE=darksky
      - DARKSKY_LATITUDE={{ latitude }}
      - DARKSKY_LONGITUDE={{ longitude }}

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - /var/homelabos/docs:/docs
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:docs.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=8000"

  emby:
    image: emby/embyserver:latest
    restart: always
    volumes:
      - /var/homelabos/emby:/config
    ports:
      - 8096:8096
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:emby.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=8096"


  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    links:
      - gitea_db:db
    volumes:
      - ./gitea:/data
    ports:
      - "3030:3000"
      - "222:22"
    depends_on:
      - gitea_db
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:git.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=3000"

  gitea_db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - /var/homelabos/gitea_db:/var/lib/mysql


  grafana:
    image: grafana/grafana
    restart: always
    links:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - /var/homelabos/grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,natel-discrete-panel,petrslavotinek-carpetplot-panel,vonage-status-panel
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:grafana.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=3000"

  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - /var/homelabos/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    ports:
      - 8123:8123
      - 1883:1883
      # - 8080:8080
      - 51827:51827
    links:
      - influxdb
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:homeassistant.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=8123"


  influxdb:
    image: influxdb
    restart: always
    volumes:
      - /var/homelabos/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086



  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - 8181:80
    links:
      - nextcloud_db
    volumes:
      - /var/homelabos/nextcloud:/var/www/html
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:nextcloud.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=80"

  nextcloud_db:
    image: mariadb
    restart: always
    volumes:
      - /var/homelabos/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  pihole:
    image: diginc/pi-hole:latest
    restart: always
    volumes:
      - /var/homelabos/pihole/config:/etc/pihole/
      - /var/homelabos/pihole/dnsmasq.d:/etc/dnsmasq.d/"
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:pihole.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=80"

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - /var/homelabos/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb

  traefik:
    image: traefik # The official Traefik docker image
    restart: always
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443" # HTTPS
      - "8080:8080" # The Web UI (enabled by --api)
    labels:
      - "traefik.frontend.rule=Host:{{ domain }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/homelabos/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/homelabos/traefik/acme.json:/etc/traefik/acme.json

  utorrent:
    image: ekho/utorrent:latest
    volumes:
      - /var/homelabos/downloads:/utorrent/data
      - /var/homelabos/utorrent/settings:/utorrent/settings
      # - /var/homelabos/utorrent/utserver.conf:/utorrent/utserver.conf
    environment:
      HOST_UID: 1002
      HOST_GID: 1002
    ports:
      - 8082:8080
      - 6881:6881
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.admin.frontend.rule=Host:utorrent.{{ domain }}"
      - "traefik.admin.protocol=http"
      - "traefik.admin.port=8080"